[default]
description = "Default permissions for the plugin"
permissions = ["allow-enumerate", "allow-open", "allow-close", "allow-write", "allow-read", "allow-send-output-report", "allow-get-input-report"]